version: "3"

tasks:
  default:
    cmd: task -a

  tcp:connect:
    vars:
      PORT: 8080
    cmd: socat - TCP:localhost:{{.PORT}}

  uds:connect:
    vars:
      SOCKET_PATH: /tmp/echo.sock
    cmd: socat - UNIX-CONNECT:{{.SOCKET_PATH}}
